database:
  databaseName: "user_management"
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: ""
kafka:
  host: "kafka-bootstrap-cluster-1.dev.fluentum.aegislabs.work:443"
  protocol: "SASL_SSL"
  topic: "aegis.hiring"